Homepage:
    pattern:  /foursquare
    defaults: { _controller: "FourSquareModule:Index:index"}

Foursquare_Venues:
    pattern: /foursquare/getVenues/lat/{lat}/lng/{lng}
    defaults: { _controller: "FourSquareModule:Index:getVenues" }